### ISSUE TITLE
Confusion with Inside the config folder, make a copy of sample.env and rename it to .env instruction

### ISSUE THREAD

**Issue by Rykimaruh** [axelboc/taekwon#61]
When it mentions the following instructions:

"Inside the config folder, make a copy of sample.env and rename it to .env"

How can I do this? Windows won't let me rename it as .env as it requires a name prefix

**Comment by axelboc** [comment]
Hi there! Apparently it works if you add a dot at the end of the filename
too--Windows removes it automatically: https://superuser.com/a/406758/264167.
Otherwise, you'll have to open a command prompt and do it from there. Let
me know how you go.

**Comment by Rykimaruh** [comment]
adding dot after extension worked! Thanks!
